# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20161018_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateTimeField()),
                ('checkout_date', models.DateTimeField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('name', models.CharField(max_length=50)),
                ('passport_number', models.CharField(max_length=20)),
                ('is_guest', models.BooleanField(default=True, verbose_name='public')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=890),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Guest', to='hotel.Room'),
        ),
    ]
