# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20161105_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='price',
            field=models.IntegerField(default=890),
            preserve_default=False,
        ),
    ]
