# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20161106_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='checkin_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='guest',
            name='checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
