# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20161106_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(default='dand@dorf.ch', max_length=255),
            preserve_default=False,
        ),
    ]
