# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 03:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_guest_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('group', models.CharField(choices=[('01', 'Drinks'), ('02', 'Liquors'), ('03', 'Side Orders'), ('04', 'Breakfast'), ('05', 'Salads'), ('06', 'Soups'), ('07', 'Sandwiches'), ('08', 'Pork'), ('09', 'Chicken'), ('10', 'Filipino Food'), ('11', 'Potato'), ('12', 'Pasta'), ('13', 'Pork Tenderloin')], max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['room']},
        ),
        migrations.AlterField(
            model_name='guest',
            name='checkin_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 6, 3, 57, 46, 152980, tzinfo=utc)),
        ),
    ]
