# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 03:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_auto_20161106_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='checkin_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 6, 3, 59, 23, 94746, tzinfo=utc)),
        ),
    ]
