# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 04:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_auto_20161106_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['group']},
        ),
        migrations.AlterField(
            model_name='guest',
            name='checkin_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 6, 4, 1, 35, 19440, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.CharField(choices=[('01', 'Drinks'), ('02', 'Liquors'), ('03', 'Side Orders'), ('04', 'Breakfast'), ('05', 'Salads'), ('06', 'Soups'), ('07', 'Sandwiches'), ('08', 'Pork'), ('09', 'Chicken'), ('10', 'Filipino Food'), ('11', 'Potato'), ('12', 'Pasta'), ('13', 'Pork Tenderloin')], max_length=2),
        ),
    ]
