# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 13:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_auto_20161106_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['guest']},
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 11, 7, 13, 20, 46, 508976, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='guest',
            name='checkin_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 7, 13, 20, 46, 505859, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Item'),
        ),
    ]
