# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 07:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_auto_20161108_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 8, 7, 4, 9, 217477, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='checkin_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 8, 7, 3, 38, 31937, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 11, 8, 7, 3, 38, 34493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Item'),
        ),
    ]
