# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 03:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_auto_20161109_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2016, 11, 10, 3, 11, 43, 230581, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='date_to',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='checkin_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 10, 3, 11, 32, 991026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 11, 10, 3, 11, 32, 994989, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Item'),
        ),
    ]
