# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0048_auto_20161111_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Item'),
        ),
        migrations.AlterField(
            model_name='roomitem',
            name='date_to',
            field=models.DateField(null=True),
        ),
    ]
