# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0052_auto_20161111_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.CharField(choices=[('01', 'Drinks'), ('02', 'Liquors'), ('03', 'Side Orders'), ('04', 'Breakfast'), ('05', 'Salads'), ('06', 'Soups'), ('07', 'Sandwiches'), ('08', 'Pork'), ('09', 'Chicken'), ('10', 'Filipino Food'), ('11', 'Potato'), ('12', 'Pasta'), ('13', 'Pork Tenderloin'), ('98', 'Room')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Item'),
        ),
    ]
