# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0063_auto_20161124_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateField()),
                ('date_fixed', models.DateField()),
                ('severity', models.IntegerField(choices=[('00', 'note'), ('01', 'low'), ('02', 'medium'), ('03', 'high')])),
                ('category', models.IntegerField(choices=[('00', 'general'), ('01', 'sanitary'), ('02', 'electric'), ('03', 'windows/doors'), ('04', 'animals')])),
                ('comments', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.IntegerField(choices=[('00', 'Owner'), ('01', 'Management'), ('02', 'Staff'), ('03', 'External')])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Item'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Item'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Employee'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Room'),
        ),
    ]
