# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0067_auto_20161124_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('00', 'general'), ('01', 'sanitary'), ('02', 'electric'), ('03', 'windows/doors'), ('04', 'animals')], max_length=2),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_fixed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='severity',
            field=models.CharField(choices=[('00', 'note'), ('01', 'low'), ('02', 'medium'), ('03', 'high')], max_length=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('00', 'Owner'), ('01', 'Management'), ('02', 'Staff'), ('03', 'External')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Item'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Item'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='warning',
            field=models.IntegerField(default=0),
        ),
    ]
